server:
  port: 8087
  tomcat:
    #    max-connections: 2000
    uri-encoding: UTF-8
    max-threads: 1000
spring:
  application:
    name: data-bigdata
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    password:     # 密码（默认为空）
    timeout: 6000  # 连接超时时间（毫秒）
  #  multipart:
  #   enabled: true
  #   max-file-size: 10mb
  #   max-request-size: 10mb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    name: test
    url: jdbc:mysql://122.51.100.175:3306/app?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true #data_operation_v10
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 200
      initialSize: 10
      minIdle: 10
      maxWait: 60000
      validationQuery: "SELECT 'x'"
      timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
      testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      poolPreparedStatements: false  #如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。
      maxPoolPreparedStatementPerConnectionSize: 100 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      #      maxOpenPreparedStatements: 20
      async-init: true
      #      filter:
      #        slf4j:
      #          enabled: true
      #          statement-create-after-login-enabled: false
      #          statement-close-after-login-enabled: false
      #          result-set-open-after-login-enabled: false
      #          result-set-close-after-login-enabled: false
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/actuator/*,actuator"
      stat-view-servlet:
        allow: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
  resources:
    static-locations: file:${web.upload.path}
#mybatis:
#  mapper-locations: classpath*:mappers/*.xml
#   configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    root: DEBUG
#  level:
#    root: DEBUG
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSq
web:
  upload:
    path: c:/upload/